specVersion: 1.0.0
name: marketplace-subql
version: 0.0.1
runner:
  node:
    name: '@subql/node-avalanche'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  HON Marketplace Subquery Project
repository: 'https://github.com/heroesofnft/marketplace-subql'
schema:
  file: ./schema.graphql
network:
  endpoint: 'https://herotestnet.heroesofnft.com'
  chainId: 'fuji'
  subnet: '2kdzD7eps9QRC449zypVGBbrzkwFrefLzmt24tS8MxmvEBuWvP'
  # dictionary: 'https://api.subquery.network/sq/subquery/avalanche-dictionary'
dataSources:
  - kind: avalanche/Runtime
    startBlock: 43553
    options:
      abi: AsksV1_1
      address: '0x717B39602E8CabB14552E5C6D12f3e09C5993754'
    assets:
      AsksV1_1:
        file: './abis/AsksV1_1.json'
    mapping:
      file: './dist/index.js'
      handlers:
        ## ASK MODULE
        - handler: handleAskCreated
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskCreated(address indexed tokenContract, uint256 indexed tokenId, (address seller,address sellerFundsRecipient,address askCurrency,uint16 findersFeeBps, uint256 askPrice))
        - handler: handleAskPriceUpdated
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskPriceUpdated(address indexed tokenContract, uint256 indexed tokenId,(address seller,address sellerFundsRecipient,address askCurrency,uint16 findersFeeBps, uint256 askPrice))
        - handler: handleAskCanceled
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskCanceled(address indexed tokenContract, uint256 indexed tokenId,(address seller,address sellerFundsRecipient,address askCurrency,uint16 findersFeeBps, uint256 askPrice))
        - handler: handleAskFilled
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskFilled(address indexed tokenContract, uint256 indexed tokenId,address indexed buyer, address finder,(address seller,address sellerFundsRecipient,address askCurrency,uint16 findersFeeBps, uint256 askPrice))

        ## OFFER MODULE

        ## RESERVE AUCTION MODULE

        # - handler: handleBlock
        #   kind: avalanche/BlockHandler
