specVersion: 1.0.0
name: avalanche-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-avalanche'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your new Avalanche
  SubQuery project
repository: 'https://github.com/subquery/avalanche-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'https://herotestnet.heroesofnft.com'
  chainId: 'fuji'
  subnet: '2kdzD7eps9QRC449zypVGBbrzkwFrefLzmt24tS8MxmvEBuWvP'
  # dictionary: 'https://api.subquery.network/sq/subquery/avalanche-dictionary'
dataSources:
  - kind: avalanche/Runtime
    startBlock: 43553
    options:
      abi: AsksV1_1
      address: '0x717B39602E8CabB14552E5C6D12f3e09C5993754'
    assets:
      AsksV1_1:
        file: './abis/AsksV1_1.json'
    mapping:
      file: './dist/index.js'
      handlers:
        ## ASK MODULE
        - handler: handleAskCreated
          kind: avalanche/LogHandler
          filter:
          topics:
            - AskCreated(address,uint256,Ask)
        - handler: handleAskPriceUpdated
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskPriceUpdated(address,uint256,Ask)
        - handler: handleAskCanceled
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskCanceled(address,uint256,Ask)
        - handler: handleAskFilled
          kind: avalanche/LogHandler
          filter:
            topics:
              - AskFilled(address,uint256,address,address,Ask)

        ## OFFER MODULE

        ## RESERVE AUCTION MODULE

        # - handler: handleBlock
        #   kind: avalanche/BlockHandler
