specVersion: 1.0.0
name: avalanche-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-avalanche'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your new Avalanche
  SubQuery project
repository: 'https://github.com/subquery/avalanche-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'https://herotestnet.heroesofnft.com'
  chainId: 'fuji'
  subnet: '2kdzD7eps9QRC449zypVGBbrzkwFrefLzmt24tS8MxmvEBuWvP'
  # chainId: mainnet
  # subnet: C
  # endpoint: >-
  #   https://herotestnet.heroesofnft.com:443/ext/bc/2kdzD7eps9QRC449zypVGBbrzkwFrefLzmt24tS8MxmvEBuWvP/rpc
  # dictionary: 'https://api.subquery.network/sq/subquery/avalanche-dictionary'
dataSources:
  - kind: avalanche/Runtime
    startBlock: 1
    options:
      abi: AsksV1_1
      address: '0x717B39602E8CabB14552E5C6D12f3e09C5993754'
    assets:
      AsksV1_1:
        file: './abis/AsksV1_1.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleCreatedAsk
          kind: avalanche/LogHandler
          filter:
            function: AskCreated(address indexed tokenContract, uint256 indexed tokenId, Ask ask)
